import { DietPlan, Language } from './types';

export const DEFAULT_PLANS: DietPlan[] = [
  {
    id: 'plan-1',
    name: 'High Protein / Muscle',
    description: 'Focus on protein intake for muscle building.',
    targets: {
      calories: 2500,
      protein: 200,
      carbs: 250,
      fat: 80,
      fiber: 30,
      sugar: 40,
    },
    colorTheme: 'blue',
  },
  {
    id: 'plan-2',
    name: 'High Fiber / Wellness',
    description: 'Gut health focus with high vegetable intake.',
    targets: {
      calories: 2000,
      protein: 100,
      carbs: 300,
      fat: 60,
      fiber: 45,
      sugar: 35,
    },
    colorTheme: 'green',
  },
  {
    id: 'plan-3',
    name: 'Keto / Low Carb',
    description: 'Minimal carbs, higher fats.',
    targets: {
      calories: 1800,
      protein: 120,
      carbs: 30,
      fat: 140,
      fiber: 15,
      sugar: 10,
    },
    colorTheme: 'orange',
  }
];

// Base keys
export const BASE_STORAGE_KEYS = {
  PLANS: 'macromind_plans',
  ENTRIES: 'macromind_entries',
  RECIPES: 'macromind_recipes',
  SHOPPING: 'macromind_shopping_list',
  ACTIVE_PLAN: 'macromind_active_plan_id',
  THEME: 'macromind_theme',
  LANG: 'macromind_lang',
  CURRENT_USER: 'macromind_current_user',
  USERS_DB: 'macromind_users_db' // Simulating a users table
};

const EN_TRANSLATIONS = {
    tracker_tab: 'Tracker',
    profiles_tab: 'Diet Plan',
    recipes_tab: 'Recipes',
    shopping_tab: 'Shopping List',
    no_active_plan: 'No Active Plan Selected',
    create_select_msg: 'Please create or select a diet plan to start tracking.',
    go_to_plans: 'Go to Plans',
    todays_overview: "Today's Overview",
    tracking_for: 'Tracking for',
    diet_profiles: 'Diet Plan',
    manage_profiles: 'Manage different diet plans.',
    create_plan: 'Create Plan',
    no_plans: 'No diet plans created yet.',
    edit_plan: 'Edit Diet Plan',
    create_new_plan: 'Create New Plan',
    plan_name: 'Plan Name',
    plan_desc: 'Short Description',
    color_theme: 'Color Theme',
    daily_targets: 'Daily Targets',
    calories: 'Calories',
    protein: 'Protein',
    carbs: 'Carbs',
    fats: 'Fats',
    fiber: 'Fiber',
    sugar: 'Sugar',
    save_plan: 'Save Plan',
    cancel: 'Cancel',
    meal_log_empty_msg: 'No meals logged yet today.',
    meal_log_empty_hint: 'Add a meal above to get started!',
    meal_col: 'Meal',
    cals_col: 'Cals',
    prot_col: 'Prot',
    carbs_col: 'Carbs',
    fat_col: 'Fat',
    fiber_col: 'Fiber',
    sugar_col: 'Sugar',
    log_meal: 'Log a Meal',
    add_meal_btn: 'Add Meal',
    thinking: 'Thinking...',
    try_examples: 'Try: "2 eggs and toast" • "Protein shake with banana" • "Chicken stir fry"',
    analysis_error: 'Failed to analyze meal. Please try again.',
    delete_confirm: 'Are you sure you want to delete this plan?',
    delete_entry_confirm: 'Delete this meal?',
    placeholder_meal: 'e.g., Grilled chicken salad with avocado and dressing',
    unknown_error: 'An unknown error occurred',
    chef_mini_btn: 'ChefMini',
    chef_mini_title: 'ChefMini AI',
    chef_intro: 'How much of your remaining calories should this meal fill?',
    chef_target_calories: 'Target Calories',
    chef_generate: 'Generate Recipe',
    chef_generating: 'Cooking up a recipe...',
    chef_add_to_log: 'Add Recipe to Log',
    chef_ingredients: 'Ingredients',
    chef_instructions: 'Instructions',
    chef_no_remaining: 'You have hit your calorie goal! Increase your target to generate more meals.',
    chef_time: 'Time',
    chef_error: 'The chef burned the meal (Error). Try again!',
    remaining_cals: 'Remaining',
    save_recipe: 'Save to Cookbook',
    recipe_saved: 'Recipe Saved!',
    cookbook_title: 'My Cookbook',
    cookbook_desc: 'Your collection of AI-generated recipes.',
    no_recipes: 'No recipes saved yet.',
    no_recipes_hint: 'Use ChefMini to generate and save delicious recipes.',
    view_recipe: 'View Recipe',
    log_this_meal: 'Log This Meal',
    delete_recipe: 'Delete Recipe',
    chef_prompt_label: 'Any specific cravings? (Optional)',
    chef_prompt_placeholder: 'e.g. "Spicy chicken pasta", "Something vegetarian", "Quick breakfast"',
    shopping_list_title: 'Shopping List',
    shopping_list_desc: 'Manage your ingredients and grocery items.',
    add_item: 'Add Item',
    add_to_shopping: 'Add to Shopping List',
    added_to_shopping: 'Added to List',
    clear_completed: 'Clear Completed',
    no_items: 'Your shopping list is empty.',
    no_items_hint: 'Add items manually or export ingredients from your recipes.',
    confirm_delete_title: 'Confirm Deletion',
    delete_btn: 'Delete',
    delete_recipe_confirm: 'Are you sure you want to delete this recipe?',
    // Auth
    welcome_back: 'Welcome Back',
    welcome_desc: 'Log in to access your diet plans and history.',
    create_account: 'Create Account',
    create_desc: 'Start your journey to better nutrition today.',
    email_label: 'Email Address',
    password_label: 'Password',
    name_label: 'Full Name',
    login_btn: 'Log In',
    register_btn: 'Sign Up',
    continue_google: 'Continue with Google',
    continue_apple: 'Continue with Apple',
    switch_to_register: "Don't have an account? Sign up",
    switch_to_login: 'Already have an account? Log in',
    logout: 'Log Out',
    auth_error: 'Invalid credentials. Please try again.',
    auth_exists: 'User already exists.',
    guest_continue: 'Continue as Guest'
};

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: EN_TRANSLATIONS,
  tr: {
    ...EN_TRANSLATIONS,
    tracker_tab: 'Takip',
    profiles_tab: 'Diyet Planı',
    recipes_tab: 'Tarifler',
    shopping_tab: 'Alışveriş',
    no_active_plan: 'Aktif Plan Seçilmedi',
    create_select_msg: 'Takibe başlamak için lütfen bir diyet planı oluşturun veya seçin.',
    go_to_plans: 'Planlara Git',
    todays_overview: "Bugünün Özeti",
    tracking_for: 'Takip edilen:',
    diet_profiles: 'Diyet Planı',
    manage_profiles: 'Farklı diyet planlarını yönetin.',
    create_plan: 'Plan Oluştur',
    no_plans: 'Henüz diyet planı oluşturulmadı.',
    edit_plan: 'Diyet Planını Düzenle',
    create_new_plan: 'Yeni Plan Oluştur',
    plan_name: 'Plan Adı',
    plan_desc: 'Kısa Açıklama',
    color_theme: 'Renk Teması',
    daily_targets: 'Günlük Hedefler',
    calories: 'Kalori',
    protein: 'Protein',
    carbs: 'Karb',
    fats: 'Yağ',
    fiber: 'Lif',
    sugar: 'Şeker',
    save_plan: 'Planı Kaydet',
    cancel: 'İptal',
    meal_log_empty_msg: 'Bugün henüz öğün girilmedi.',
    meal_log_empty_hint: 'Başlamak için yukarıdan bir öğün ekleyin!',
    meal_col: 'Öğün',
    cals_col: 'Kal',
    prot_col: 'Prot',
    carbs_col: 'Karb',
    fat_col: 'Yağ',
    fiber_col: 'Lif',
    sugar_col: 'Şeker',
    log_meal: 'Öğün Ekle',
    add_meal_btn: 'Ekle',
    thinking: 'Düşünüyor...',
    try_examples: 'Örnek: "2 yumurta ve tost" • "Muzlu protein shake" • "Tavuk sote"',
    analysis_error: 'Öğün analiz edilemedi. Lütfen tekrar deneyin.',
    delete_confirm: 'Bu planı silmek istediğinize emin misiniz?',
    delete_entry_confirm: 'Bu öğün silinsin mi?',
    placeholder_meal: 'Örn: Avokadolu ve soslu ızgara tavuk salatası',
    unknown_error: 'Bilinmeyen bir hata oluştu',
    chef_mini_btn: 'ChefMini',
    chef_mini_title: 'ChefMini AI',
    chef_intro: 'Kalan kalorinin ne kadarını bu öğünle doldurmak istersiniz?',
    chef_target_calories: 'Hedef Kalori',
    chef_generate: 'Tarif Oluştur',
    chef_generating: 'Tarif hazırlanıyor...',
    chef_add_to_log: 'Tarifi Günlüğe Ekle',
    chef_ingredients: 'Malzemeler',
    chef_instructions: 'Hazırlanışı',
    chef_no_remaining: 'Kalori hedefine ulaştın! Daha fazla öğün için hedefini yükselt.',
    chef_time: 'Süre',
    chef_error: 'Şef yemeği yaktı (Hata). Tekrar deneyin!',
    remaining_cals: 'Kalan',
    save_recipe: 'Tarif Defterine Kaydet',
    recipe_saved: 'Tarif Kaydedildi!',
    cookbook_title: 'Tarif Defterim',
    cookbook_desc: 'AI tarafından oluşturulan tarif koleksiyonunuz.',
    no_recipes: 'Henüz kaydedilmiş tarif yok.',
    no_recipes_hint: 'Lezzetli tarifler oluşturmak ve kaydetmek için ChefMini\'yi kullanın.',
    view_recipe: 'Tarifi Görüntüle',
    log_this_meal: 'Bu Öğünü Ekle',
    delete_recipe: 'Tarifi Sil',
    chef_prompt_label: 'Özel bir isteğiniz var mı? (İsteğe bağlı)',
    chef_prompt_placeholder: 'Örn: "Acılı tavuklu makarna", "Vejetaryen bir şeyler", "Pratik kahvaltı"',
    shopping_list_title: 'Alışveriş Listesi',
    shopping_list_desc: 'Malzemelerinizi ve market alışverişinizi yönetin.',
    add_item: 'Ekle',
    add_to_shopping: 'Alışveriş Listesine Ekle',
    added_to_shopping: 'Listeye Eklendi',
    clear_completed: 'Tamamlananları Temizle',
    no_items: 'Alışveriş listeniz boş.',
    no_items_hint: 'Manuel olarak ekleyin veya tariflerden malzeme aktarın.',
    confirm_delete_title: 'Silme Onayı',
    delete_btn: 'Sil',
    delete_recipe_confirm: 'Bu tarifi silmek istediğinize emin misiniz?',
    welcome_back: 'Tekrar Hoşgeldiniz',
    welcome_desc: 'Diyet planlarınıza erişmek için giriş yapın.',
    create_account: 'Hesap Oluştur',
    create_desc: 'Daha iyi beslenme yolculuğunuza bugün başlayın.',
    email_label: 'E-posta Adresi',
    password_label: 'Şifre',
    name_label: 'Ad Soyad',
    login_btn: 'Giriş Yap',
    register_btn: 'Kayıt Ol',
    continue_google: 'Google ile devam et',
    continue_apple: 'Apple ile devam et',
    switch_to_register: "Hesabınız yok mu? Kayıt olun",
    switch_to_login: 'Zaten hesabınız var mı? Giriş yapın',
    logout: 'Çıkış Yap',
    auth_error: 'Geçersiz bilgiler. Tekrar deneyin.',
    auth_exists: 'Kullanıcı zaten mevcut.',
    guest_continue: 'Misafir Olarak Devam Et'
  },
  de: {
    ...EN_TRANSLATIONS,
    tracker_tab: 'Tracker',
    profiles_tab: 'Ernährungsplan',
    recipes_tab: 'Rezepte',
    shopping_tab: 'Einkaufsliste',
    no_active_plan: 'Kein aktiver Plan ausgewählt',
    create_select_msg: 'Bitte erstellen oder wählen Sie einen Ernährungsplan, um zu beginnen.',
    go_to_plans: 'Zu den Plänen',
    todays_overview: "Heutige Übersicht",
    tracking_for: 'Tracking für',
    diet_profiles: 'Ernährungsplan',
    manage_profiles: 'Verwalten Sie verschiedene Ernährungspläne.',
    create_plan: 'Plan erstellen',
    no_plans: 'Noch keine Pläne erstellt.',
    edit_plan: 'Plan bearbeiten',
    create_new_plan: 'Neuen Plan erstellen',
    plan_name: 'Planname',
    plan_desc: 'Kurzbeschreibung',
    color_theme: 'Farbthema',
    daily_targets: 'Tagesziele',
    calories: 'Kalorien',
    protein: 'Protein',
    carbs: 'Kohlenhydrate',
    fats: 'Fett',
    fiber: 'Ballaststoffe',
    sugar: 'Zucker',
    save_plan: 'Plan speichern',
    cancel: 'Abbrechen',
    meal_log_empty_msg: 'Heute noch keine Mahlzeiten eingetragen.',
    meal_log_empty_hint: 'Fügen Sie oben eine Mahlzeit hinzu, um zu beginnen!',
    meal_col: 'Mahlzeit',
    cals_col: 'Kcal',
    prot_col: 'Prot',
    carbs_col: 'Kh',
    fat_col: 'Fett',
    fiber_col: 'Bal.',
    sugar_col: 'Zucker',
    log_meal: 'Mahlzeit eintragen',
    add_meal_btn: 'Hinzufügen',
    thinking: 'Denkt nach...',
    try_examples: 'Versuchen Sie: "2 Eier und Toast" • "Proteinshake mit Banane" • "Hühnchenpfanne"',
    analysis_error: 'Fehler bei der Analyse. Bitte versuchen Sie es erneut.',
    delete_confirm: 'Sind Sie sicher, dass Sie diesen Plan löschen möchten?',
    delete_entry_confirm: 'Diese Mahlzeit löschen?',
    placeholder_meal: 'z.B. Gegrillter Hähnchensalat mit Avocado',
    unknown_error: 'Ein unbekannter Fehler ist aufgetreten',
    chef_mini_btn: 'ChefMini',
    chef_mini_title: 'ChefMini AI',
    chef_intro: 'Wie viel Ihrer verbleibenden Kalorien soll diese Mahlzeit füllen?',
    chef_target_calories: 'Zielkalorien',
    chef_generate: 'Rezept erstellen',
    chef_generating: 'Kocht ein Rezept...',
    chef_add_to_log: 'Zum Tagebuch hinzufügen',
    chef_ingredients: 'Zutaten',
    chef_instructions: 'Anleitung',
    chef_no_remaining: 'Kalorienziel erreicht! Erhöhen Sie Ihr Ziel für mehr Mahlzeiten.',
    chef_time: 'Zeit',
    chef_error: 'Der Chef hat das Essen verbrannt (Fehler). Versuchen Sie es erneut!',
    remaining_cals: 'Verbleibend',
    save_recipe: 'Im Kochbuch speichern',
    recipe_saved: 'Rezept gespeichert!',
    cookbook_title: 'Mein Kochbuch',
    cookbook_desc: 'Ihre Sammlung von KI-generierten Rezepten.',
    no_recipes: 'Noch keine Rezepte gespeichert.',
    no_recipes_hint: 'Nutzen Sie ChefMini, um leckere Rezepte zu erstellen und zu speichern.',
    view_recipe: 'Rezept ansehen',
    log_this_meal: 'Diese Mahlzeit loggen',
    delete_recipe: 'Rezept löschen',
    chef_prompt_label: 'Spezielle Wünsche? (Optional)',
    chef_prompt_placeholder: 'z.B. "Scharfe Hähnchenpasta", "Etwas Vegetarisches", "Schnelles Frühstück"',
    shopping_list_title: 'Einkaufsliste',
    shopping_list_desc: 'Verwalten Sie Ihre Zutaten und Einkäufe.',
    add_item: 'Artikel hinzufügen',
    add_to_shopping: 'Zur Einkaufsliste',
    added_to_shopping: 'Hinzugefügt',
    clear_completed: 'Erledigte löschen',
    no_items: 'Ihre Einkaufsliste ist leer.',
    no_items_hint: 'Fügen Sie Artikel manuell hinzu oder exportieren Sie Zutaten aus Rezepten.',
    confirm_delete_title: 'Löschen bestätigen',
    delete_btn: 'Löschen',
    delete_recipe_confirm: 'Sind Sie sicher, dass Sie dieses Rezept löschen möchten?',
    welcome_back: 'Willkommen zurück',
    welcome_desc: 'Melden Sie sich an, um auf Ihre Pläne zuzugreifen.',
    create_account: 'Konto erstellen',
    create_desc: 'Starten Sie noch heute Ihre Reise zu besserer Ernährung.',
    email_label: 'E-Mail Adresse',
    password_label: 'Passwort',
    name_label: 'Vollständiger Name',
    login_btn: 'Anmelden',
    register_btn: 'Registrieren',
    continue_google: 'Mit Google fortfahren',
    continue_apple: 'Mit Apple fortfahren',
    switch_to_register: "Kein Konto? Registrieren",
    switch_to_login: 'Haben Sie ein Konto? Anmelden',
    logout: 'Abmelden',
    auth_error: 'Ungültige Anmeldedaten.',
    auth_exists: 'Benutzer existiert bereits.',
    guest_continue: 'Als Gast fortfahren'
  },
  fr: {
    ...EN_TRANSLATIONS,
    tracker_tab: 'Suivi',
    profiles_tab: 'Régime',
    recipes_tab: 'Recettes',
    shopping_tab: 'Courses',
    no_active_plan: 'Aucun plan actif',
    create_select_msg: 'Veuillez créer ou sélectionner un plan pour commencer.',
    go_to_plans: 'Voir les plans',
    todays_overview: "Aperçu du jour",
    tracking_for: 'Suivi pour',
    diet_profiles: 'Plan Régime',
    manage_profiles: 'Gérez différents plans alimentaires.',
    create_plan: 'Créer un plan',
    no_plans: 'Aucun plan créé pour le moment.',
    edit_plan: 'Modifier le plan',
    create_new_plan: 'Créer un nouveau plan',
    plan_name: 'Nom du plan',
    plan_desc: 'Description courte',
    color_theme: 'Thème couleur',
    daily_targets: 'Objectifs quotidiens',
    calories: 'Calories',
    protein: 'Protéines',
    carbs: 'Glucides',
    fats: 'Lipides',
    fiber: 'Fibres',
    sugar: 'Sucre',
    save_plan: 'Enregistrer',
    cancel: 'Annuler',
    meal_log_empty_msg: 'Aucun repas enregistré aujourd\'hui.',
    meal_log_empty_hint: 'Ajoutez un repas ci-dessus pour commencer !',
    meal_col: 'Repas',
    cals_col: 'Cal',
    prot_col: 'Prot',
    carbs_col: 'Gluc',
    fat_col: 'Lip',
    fiber_col: 'Fib',
    sugar_col: 'Sucre',
    log_meal: 'Ajouter un repas',
    add_meal_btn: 'Ajouter',
    thinking: 'Réflexion...',
    try_examples: 'Essayez : "2 œufs et toast" • "Shake protéiné banane" • "Poulet sauté"',
    analysis_error: 'Échec de l\'analyse. Veuillez réessayer.',
    delete_confirm: 'Êtes-vous sûr de vouloir supprimer ce plan ?',
    delete_entry_confirm: 'Supprimer ce repas ?',
    placeholder_meal: 'ex: Salade de poulet grillé avec avocat',
    unknown_error: 'Une erreur inconnue est survenue',
    chef_mini_btn: 'ChefMini',
    chef_mini_title: 'ChefMini IA',
    chef_intro: 'Quelle part de vos calories restantes ce repas doit-il combler ?',
    chef_target_calories: 'Calories cibles',
    chef_generate: 'Générer la recette',
    chef_generating: 'Préparation de la recette...',
    chef_add_to_log: 'Ajouter au journal',
    chef_ingredients: 'Ingrédients',
    chef_instructions: 'Instructions',
    chef_no_remaining: 'Objectif atteint ! Augmentez votre cible pour plus de repas.',
    chef_time: 'Temps',
    chef_error: 'Le chef a brûlé le repas (Erreur). Réessayez !',
    remaining_cals: 'Restant',
    save_recipe: 'Sauvegarder',
    recipe_saved: 'Recette sauvegardée !',
    cookbook_title: 'Mon Livre de Recettes',
    cookbook_desc: 'Votre collection de recettes générées par IA.',
    no_recipes: 'Aucune recette sauvegardée.',
    no_recipes_hint: 'Utilisez ChefMini pour générer des recettes.',
    view_recipe: 'Voir la recette',
    log_this_meal: 'Journaliser ce repas',
    delete_recipe: 'Supprimer la recette',
    chef_prompt_label: 'Envies spécifiques ? (Optionnel)',
    chef_prompt_placeholder: 'ex: "Pâtes poulet épicé", "Végétarien", "Petit-déj rapide"',
    shopping_list_title: 'Liste de Courses',
    shopping_list_desc: 'Gérez vos ingrédients et achats.',
    add_item: 'Ajouter',
    add_to_shopping: 'Ajouter à la liste',
    added_to_shopping: 'Ajouté',
    clear_completed: 'Effacer complétés',
    no_items: 'Votre liste est vide.',
    no_items_hint: 'Ajoutez manuellement ou depuis les recettes.',
    confirm_delete_title: 'Confirmer la suppression',
    delete_btn: 'Supprimer',
    delete_recipe_confirm: 'Êtes-vous sûr de vouloir supprimer cette recette ?',
    welcome_back: 'Bon retour',
    welcome_desc: 'Connectez-vous pour accéder à vos plans.',
    create_account: 'Créer un compte',
    create_desc: 'Commencez votre voyage nutritionnel aujourd\'hui.',
    email_label: 'Adresse e-mail',
    password_label: 'Mot de passe',
    name_label: 'Nom complet',
    login_btn: 'Connexion',
    register_btn: 'S\'inscrire',
    continue_google: 'Continuer avec Google',
    continue_apple: 'Continuer avec Apple',
    switch_to_register: "Pas de compte ? S'inscrire",
    switch_to_login: 'Déjà un compte ? Connexion',
    logout: 'Déconnexion',
    auth_error: 'Identifiants invalides.',
    auth_exists: 'L\'utilisateur existe déjà.',
    guest_continue: 'Continuer en invité'
  },
  nl: {
    ...EN_TRANSLATIONS,
    tracker_tab: 'Tracker',
    profiles_tab: 'Dieetplan',
    recipes_tab: 'Recepten',
    shopping_tab: 'Boodschappen',
    no_active_plan: 'Geen actief plan',
    create_select_msg: 'Maak of selecteer een dieetplan om te beginnen.',
    go_to_plans: 'Naar plannen',
    todays_overview: "Overzicht Vandaag",
    tracking_for: 'Tracking voor',
    diet_profiles: 'Dieetplan',
    manage_profiles: 'Beheer verschillende dieetplannen.',
    create_plan: 'Plan maken',
    no_plans: 'Nog geen plannen gemaakt.',
    edit_plan: 'Plan bewerken',
    create_new_plan: 'Nieuw plan maken',
    plan_name: 'Plannaam',
    plan_desc: 'Korte beschrijving',
    color_theme: 'Kleurthema',
    daily_targets: 'Dagelijkse doelen',
    calories: 'Calorieën',
    protein: 'Eiwit',
    carbs: 'Koolhydraten',
    fats: 'Vetten',
    fiber: 'Vezels',
    sugar: 'Suiker',
    save_plan: 'Plan opslaan',
    cancel: 'Annuleren',
    meal_log_empty_msg: 'Nog geen maaltijden gelogd vandaag.',
    meal_log_empty_hint: 'Voeg hierboven een maaltijd toe om te beginnen!',
    meal_col: 'Maaltijd',
    cals_col: 'Kcal',
    prot_col: 'Eiwit',
    carbs_col: 'Koolh',
    fat_col: 'Vet',
    fiber_col: 'Vezel',
    sugar_col: 'Suiker',
    log_meal: 'Maaltijd loggen',
    add_meal_btn: 'Toevoegen',
    thinking: 'Denken...',
    try_examples: 'Probeer: "2 eieren en toast" • "Eiwitshake met banaan"',
    analysis_error: 'Kon maaltijd niet analyseren. Probeer opnieuw.',
    delete_confirm: 'Weet u zeker dat u dit plan wilt verwijderen?',
    delete_entry_confirm: 'Deze maaltijd verwijderen?',
    placeholder_meal: 'bijv. Gegrilde kipsalade met avocado',
    unknown_error: 'Er is een onbekende fout opgetreden',
    chef_mini_btn: 'ChefMini',
    chef_mini_title: 'ChefMini AI',
    chef_intro: 'Hoeveel van uw resterende calorieën moet deze maaltijd vullen?',
    chef_target_calories: 'Doelcalorieën',
    chef_generate: 'Recept genereren',
    chef_generating: 'Recept koken...',
    chef_add_to_log: 'Toevoegen aan logboek',
    chef_ingredients: 'Ingrediënten',
    chef_instructions: 'Instructies',
    chef_no_remaining: 'Caloriedoel bereikt! Verhoog uw doel voor meer maaltijden.',
    chef_time: 'Tijd',
    chef_error: 'De chef heeft het eten laten aanbranden (Fout). Probeer opnieuw!',
    remaining_cals: 'Resterend',
    save_recipe: 'Opslaan in kookboek',
    recipe_saved: 'Recept opgeslagen!',
    cookbook_title: 'Mijn Kookboek',
    cookbook_desc: 'Uw verzameling AI-gegenereerde recepten.',
    no_recipes: 'Nog geen recepten opgeslagen.',
    no_recipes_hint: 'Gebruik ChefMini om recepten te maken.',
    view_recipe: 'Bekijk Recept',
    log_this_meal: 'Log Deze Maaltijd',
    delete_recipe: 'Recept Verwijderen',
    chef_prompt_label: 'Specifieke wensen? (Optioneel)',
    chef_prompt_placeholder: 'bijv. "Pittige kippasta", "Iets vegetarisch"',
    shopping_list_title: 'Boodschappenlijst',
    shopping_list_desc: 'Beheer uw ingrediënten.',
    add_item: 'Item toevoegen',
    add_to_shopping: 'Naar boodschappenlijst',
    added_to_shopping: 'Toegevoegd',
    clear_completed: 'Voltooide wissen',
    no_items: 'Uw boodschappenlijst is leeg.',
    no_items_hint: 'Voeg items handmatig toe of via recepten.',
    confirm_delete_title: 'Verwijderen bevestigen',
    delete_btn: 'Verwijderen',
    delete_recipe_confirm: 'Weet u zeker dat u dit recept wilt verwijderen?',
    welcome_back: 'Welkom terug',
    welcome_desc: 'Log in om toegang te krijgen tot uw plannen.',
    create_account: 'Account aanmaken',
    create_desc: 'Begin vandaag met uw voedingsreis.',
    email_label: 'E-mailadres',
    password_label: 'Wachtwoord',
    name_label: 'Volledige naam',
    login_btn: 'Inloggen',
    register_btn: 'Aanmelden',
    continue_google: 'Doorgaan met Google',
    continue_apple: 'Doorgaan met Apple',
    switch_to_register: "Geen account? Aanmelden",
    switch_to_login: 'Heeft u al een account? Inloggen',
    logout: 'Uitloggen',
    auth_error: 'Ongeldige inloggegevens.',
    auth_exists: 'Gebruiker bestaat al.',
    guest_continue: 'Doorgaan als gast'
  },
  es: {
    ...EN_TRANSLATIONS,
    tracker_tab: 'Seguimiento',
    profiles_tab: 'Plan de Dieta',
    recipes_tab: 'Recetas',
    shopping_tab: 'Compras',
    no_active_plan: 'Ningún plan activo',
    create_select_msg: 'Por favor cree o seleccione un plan para comenzar.',
    go_to_plans: 'Ir a Planes',
    todays_overview: "Resumen de Hoy",
    tracking_for: 'Seguimiento para',
    diet_profiles: 'Plan de Dieta',
    manage_profiles: 'Administra diferentes planes de dieta.',
    create_plan: 'Crear Plan',
    no_plans: 'Aún no hay planes creados.',
    edit_plan: 'Editar Plan',
    create_new_plan: 'Crear Nuevo Plan',
    plan_name: 'Nombre del Plan',
    plan_desc: 'Descripción Corta',
    color_theme: 'Tema de Color',
    daily_targets: 'Objetivos Diarios',
    calories: 'Calorías',
    protein: 'Proteína',
    carbs: 'Carbohidratos',
    fats: 'Grasas',
    fiber: 'Fibra',
    sugar: 'Azúcar',
    save_plan: 'Guardar Plan',
    cancel: 'Cancelar',
    meal_log_empty_msg: 'Aún no se han registrado comidas hoy.',
    meal_log_empty_hint: '¡Añade una comida arriba para empezar!',
    meal_col: 'Comida',
    cals_col: 'Cal',
    prot_col: 'Prot',
    carbs_col: 'Carb',
    fat_col: 'Grasa',
    fiber_col: 'Fibra',
    sugar_col: 'Azúcar',
    log_meal: 'Registrar Comida',
    add_meal_btn: 'Añadir',
    thinking: 'Pensando...',
    try_examples: 'Prueba: "2 huevos y tostada" • "Batido de proteína con plátano"',
    analysis_error: 'Fallo al analizar la comida. Inténtalo de nuevo.',
    delete_confirm: '¿Estás seguro de que quieres eliminar este plan?',
    delete_entry_confirm: '¿Eliminar esta comida?',
    placeholder_meal: 'ej: Ensalada de pollo a la parrilla con aguacate',
    unknown_error: 'Ocurrió un error desconocido',
    chef_mini_btn: 'ChefMini',
    chef_mini_title: 'ChefMini IA',
    chef_intro: '¿Cuánto de tus calorías restantes debe llenar esta comida?',
    chef_target_calories: 'Calorías Objetivo',
    chef_generate: 'Generar Receta',
    chef_generating: 'Cocinando una receta...',
    chef_add_to_log: 'Añadir al Diario',
    chef_ingredients: 'Ingredientes',
    chef_instructions: 'Instrucciones',
    chef_no_remaining: '¡Has alcanzado tu objetivo! Aumenta tu meta para más comidas.',
    chef_time: 'Tiempo',
    chef_error: 'El chef quemó la comida (Error). ¡Inténtalo de nuevo!',
    remaining_cals: 'Restante',
    save_recipe: 'Guardar en Libro',
    recipe_saved: '¡Receta Guardada!',
    cookbook_title: 'Mi Libro de Cocina',
    cookbook_desc: 'Tu colección de recetas generadas por IA.',
    no_recipes: 'Aún no hay recetas guardadas.',
    no_recipes_hint: 'Usa ChefMini para generar recetas deliciosas.',
    view_recipe: 'Ver Receta',
    log_this_meal: 'Registrar esta Comida',
    delete_recipe: 'Eliminar Receta',
    chef_prompt_label: '¿Antojos específicos? (Opcional)',
    chef_prompt_placeholder: 'ej: "Pasta con pollo picante", "Algo vegetariano"',
    shopping_list_title: 'Lista de Compras',
    shopping_list_desc: 'Administra tus ingredientes y compras.',
    add_item: 'Añadir Artículo',
    add_to_shopping: 'Añadir a la Lista',
    added_to_shopping: 'Añadido',
    clear_completed: 'Borrar Completados',
    no_items: 'Tu lista de compras está vacía.',
    no_items_hint: 'Añade artículos manualmente o exporta ingredientes.',
    confirm_delete_title: 'Confirmar Eliminación',
    delete_btn: 'Eliminar',
    delete_recipe_confirm: '¿Estás seguro de que quieres eliminar esta receta?',
    welcome_back: 'Bienvenido de nuevo',
    welcome_desc: 'Inicia sesión para acceder a tus planes.',
    create_account: 'Crear Cuenta',
    create_desc: 'Comienza tu viaje de nutrición hoy.',
    email_label: 'Correo Electrónico',
    password_label: 'Contraseña',
    name_label: 'Nombre Completo',
    login_btn: 'Iniciar Sesión',
    register_btn: 'Registrarse',
    continue_google: 'Continuar con Google',
    continue_apple: 'Continuar con Apple',
    switch_to_register: "¿No tienes cuenta? Regístrate",
    switch_to_login: '¿Ya tienes cuenta? Inicia sesión',
    logout: 'Cerrar Sesión',
    auth_error: 'Credenciales inválidas.',
    auth_exists: 'El usuario ya existe.',
    guest_continue: 'Continuar como Invitado'
  },
  pt: {
    ...EN_TRANSLATIONS,
    tracker_tab: 'Rastreador',
    profiles_tab: 'Plano de Dieta',
    recipes_tab: 'Receitas',
    shopping_tab: 'Compras',
    no_active_plan: 'Nenhum plano ativo',
    create_select_msg: 'Crie ou selecione um plano para começar.',
    go_to_plans: 'Ir para Planos',
    todays_overview: "Visão Geral de Hoje",
    tracking_for: 'Rastreando para',
    diet_profiles: 'Plano de Dieta',
    manage_profiles: 'Gerencie diferentes planos de dieta.',
    create_plan: 'Criar Plano',
    no_plans: 'Nenhum plano criado ainda.',
    edit_plan: 'Editar Plano',
    create_new_plan: 'Criar Novo Plano',
    plan_name: 'Nome do Plano',
    plan_desc: 'Descrição Curta',
    color_theme: 'Tema de Cor',
    daily_targets: 'Metas Diárias',
    calories: 'Calorias',
    protein: 'Proteína',
    carbs: 'Carboidratos',
    fats: 'Gorduras',
    fiber: 'Fibra',
    sugar: 'Açúcar',
    save_plan: 'Salvar Plano',
    cancel: 'Cancelar',
    meal_log_empty_msg: 'Nenhuma refeição registrada hoje.',
    meal_log_empty_hint: 'Adicione uma refeição acima para começar!',
    meal_col: 'Refeição',
    cals_col: 'Cal',
    prot_col: 'Prot',
    carbs_col: 'Carb',
    fat_col: 'Gord',
    fiber_col: 'Fibra',
    sugar_col: 'Açúcar',
    log_meal: 'Registrar Refeição',
    add_meal_btn: 'Adicionar',
    thinking: 'Pensando...',
    try_examples: 'Tente: "2 ovos e torrada" • "Shake de proteína com banana"',
    analysis_error: 'Falha ao analisar a refeição. Tente novamente.',
    delete_confirm: 'Tem certeza que deseja excluir este plano?',
    delete_entry_confirm: 'Excluir esta refeição?',
    placeholder_meal: 'ex: Salada de frango grelhado com abacate',
    unknown_error: 'Ocorreu um erro desconhecido',
    chef_mini_btn: 'ChefMini',
    chef_mini_title: 'ChefMini IA',
    chef_intro: 'Quanto das suas calorias restantes esta refeição deve preencher?',
    chef_target_calories: 'Calorias Alvo',
    chef_generate: 'Gerar Receita',
    chef_generating: 'Cozinhando uma receita...',
    chef_add_to_log: 'Adicionar ao Diário',
    chef_ingredients: 'Ingredientes',
    chef_instructions: 'Instruções',
    chef_no_remaining: 'Você atingiu sua meta! Aumente seu alvo para mais refeições.',
    chef_time: 'Tempo',
    chef_error: 'O chef queimou a comida (Erro). Tente novamente!',
    remaining_cals: 'Restante',
    save_recipe: 'Salvar no Livro',
    recipe_saved: 'Receita Salva!',
    cookbook_title: 'Meu Livro de Receitas',
    cookbook_desc: 'Sua coleção de receitas geradas por IA.',
    no_recipes: 'Nenhuma receita salva ainda.',
    no_recipes_hint: 'Use ChefMini para gerar e salvar receitas deliciosas.',
    view_recipe: 'Ver Receita',
    log_this_meal: 'Registrar Refeição',
    delete_recipe: 'Excluir Receita',
    chef_prompt_label: 'Desejos específicos? (Opcional)',
    chef_prompt_placeholder: 'ex: "Macarrão com frango picante", "Algo vegetariano"',
    shopping_list_title: 'Lista de Compras',
    shopping_list_desc: 'Gerencie seus ingredientes e compras.',
    add_item: 'Adicionar Item',
    add_to_shopping: 'Adicionar à Lista',
    added_to_shopping: 'Adicionado',
    clear_completed: 'Limpar Concluídos',
    no_items: 'Sua lista de compras está vazia.',
    no_items_hint: 'Adicione itens manualmente ou exporte de receitas.',
    confirm_delete_title: 'Confirmar Exclusão',
    delete_btn: 'Excluir',
    delete_recipe_confirm: 'Tem certeza que deseja excluir esta receita?',
    welcome_back: 'Bem-vindo de volta',
    welcome_desc: 'Faça login para acessar seus planos.',
    create_account: 'Criar Conta',
    create_desc: 'Comece sua jornada de nutrição hoje.',
    email_label: 'E-mail',
    password_label: 'Senha',
    name_label: 'Nome Completo',
    login_btn: 'Entrar',
    register_btn: 'Cadastrar',
    continue_google: 'Continuar com Google',
    continue_apple: 'Continuar com Apple',
    switch_to_register: "Não tem conta? Cadastre-se",
    switch_to_login: 'Já tem conta? Entrar',
    logout: 'Sair',
    auth_error: 'Credenciais inválidas.',
    auth_exists: 'Usuário já existe.',
    guest_continue: 'Continuar como Convidado'
  },
  ru: {
    ...EN_TRANSLATIONS,
    tracker_tab: 'Трекер',
    profiles_tab: 'План диеты',
    recipes_tab: 'Рецепты',
    shopping_tab: 'Покупки',
    no_active_plan: 'Нет активного плана',
    create_select_msg: 'Создайте или выберите план диеты, чтобы начать.',
    go_to_plans: 'К планам',
    todays_overview: "Обзор за сегодня",
    tracking_for: 'Отслеживание для',
    diet_profiles: 'План диеты',
    manage_profiles: 'Управляйте планами диеты.',
    create_plan: 'Создать план',
    no_plans: 'Планов пока нет.',
    edit_plan: 'Редактировать',
    create_new_plan: 'Новый план',
    plan_name: 'Название',
    plan_desc: 'Описание',
    color_theme: 'Цвет',
    daily_targets: 'Цели на день',
    calories: 'Калории',
    protein: 'Белки',
    carbs: 'Углеводы',
    fats: 'Жиры',
    fiber: 'Клетчатка',
    sugar: 'Сахар',
    save_plan: 'Сохранить',
    cancel: 'Отмена',
    meal_log_empty_msg: 'Сегодня записей нет.',
    meal_log_empty_hint: 'Добавьте блюдо выше, чтобы начать!',
    meal_col: 'Блюдо',
    cals_col: 'Ккал',
    prot_col: 'Бел',
    carbs_col: 'Угл',
    fat_col: 'Жир',
    fiber_col: 'Клет',
    sugar_col: 'Сах',
    log_meal: 'Добавить',
    add_meal_btn: 'Добавить',
    thinking: 'Думаю...',
    try_examples: 'Попробуйте: "2 яйца и тост" • "Протеиновый коктейль"',
    analysis_error: 'Ошибка анализа. Попробуйте снова.',
    delete_confirm: 'Вы уверены, что хотите удалить этот план?',
    delete_entry_confirm: 'Удалить это блюдо?',
    placeholder_meal: 'напр., Салат с курицей и авокадо',
    unknown_error: 'Неизвестная ошибка',
    chef_mini_btn: 'ШефМини',
    chef_mini_title: 'ШефМини ИИ',
    chef_intro: 'Сколько оставшихся калорий должно заполнить это блюдо?',
    chef_target_calories: 'Целевые калории',
    chef_generate: 'Создать рецепт',
    chef_generating: 'Готовлю рецепт...',
    chef_add_to_log: 'Добавить в журнал',
    chef_ingredients: 'Ингредиенты',
    chef_instructions: 'Инструкции',
    chef_no_remaining: 'Цель достигнута! Увеличьте цель для новых блюд.',
    chef_time: 'Время',
    chef_error: 'Шеф сжег еду (Ошибка). Попробуйте снова!',
    remaining_cals: 'Осталось',
    save_recipe: 'Сохранить',
    recipe_saved: 'Сохранено!',
    cookbook_title: 'Моя Кулинарная Книга',
    cookbook_desc: 'Ваша коллекция рецептов от ИИ.',
    no_recipes: 'Рецептов пока нет.',
    no_recipes_hint: 'Используйте ШефМини для создания рецептов.',
    view_recipe: 'Посмотреть',
    log_this_meal: 'Записать блюдо',
    delete_recipe: 'Удалить рецепт',
    chef_prompt_label: 'Пожелания? (Опционально)',
    chef_prompt_placeholder: 'напр. "Острая паста с курицей", "Что-то вегетарианское"',
    shopping_list_title: 'Список покупок',
    shopping_list_desc: 'Управляйте ингредиентами.',
    add_item: 'Добавить',
    add_to_shopping: 'В список покупок',
    added_to_shopping: 'Добавлено',
    clear_completed: 'Очистить',
    no_items: 'Список покупок пуст.',
    no_items_hint: 'Добавьте вручную или из рецептов.',
    confirm_delete_title: 'Подтвердите удаление',
    delete_btn: 'Удалить',
    delete_recipe_confirm: 'Вы уверены, что хотите удалить этот рецепт?',
    welcome_back: 'С возвращением',
    welcome_desc: 'Войдите, чтобы получить доступ к планам.',
    create_account: 'Создать аккаунт',
    create_desc: 'Начните путь к лучшему питанию.',
    email_label: 'Email',
    password_label: 'Пароль',
    name_label: 'Имя',
    login_btn: 'Войти',
    register_btn: 'Регистрация',
    continue_google: 'Войти через Google',
    continue_apple: 'Войти через Apple',
    switch_to_register: "Нет аккаунта? Зарегистрируйтесь",
    switch_to_login: 'Есть аккаунт? Войдите',
    logout: 'Выйти',
    auth_error: 'Неверные данные.',
    auth_exists: 'Пользователь уже существует.',
    guest_continue: 'Продолжить как гость'
  },
  zh: {
    ...EN_TRANSLATIONS,
    tracker_tab: '追踪',
    profiles_tab: '饮食计划',
    recipes_tab: '食谱',
    shopping_tab: '购物清单',
    no_active_plan: '未选择活动计划',
    create_select_msg: '请创建或选择一个饮食计划以开始追踪。',
    go_to_plans: '去计划',
    todays_overview: "今日概览",
    tracking_for: '追踪目标：',
    diet_profiles: '饮食计划',
    manage_profiles: '管理不同的饮食计划。',
    create_plan: '创建计划',
    no_plans: '尚未创建饮食计划。',
    edit_plan: '编辑计划',
    create_new_plan: '创建新计划',
    plan_name: '计划名称',
    plan_desc: '简短描述',
    color_theme: '颜色主题',
    daily_targets: '每日目标',
    calories: '卡路里',
    protein: '蛋白质',
    carbs: '碳水',
    fats: '脂肪',
    fiber: '纤维',
    sugar: '糖',
    save_plan: '保存计划',
    cancel: '取消',
    meal_log_empty_msg: '今天尚未记录餐点。',
    meal_log_empty_hint: '在上方添加餐点以开始！',
    meal_col: '餐点',
    cals_col: '卡路里',
    prot_col: '蛋',
    carbs_col: '碳',
    fat_col: '脂',
    fiber_col: '纤',
    sugar_col: '糖',
    log_meal: '记录餐点',
    add_meal_btn: '添加',
    thinking: '思考中...',
    try_examples: '尝试："2个鸡蛋和吐司" • "香蕉蛋白奶昔" • "炒鸡肉"',
    analysis_error: '分析失败。请重试。',
    delete_confirm: '确定要删除此计划吗？',
    delete_entry_confirm: '删除此餐点？',
    placeholder_meal: '例如：烤鸡肉沙拉配牛油果',
    unknown_error: '发生未知错误',
    chef_mini_btn: 'ChefMini',
    chef_mini_title: 'ChefMini AI',
    chef_intro: '这顿饭应该填补多少剩余卡路里？',
    chef_target_calories: '目标卡路里',
    chef_generate: '生成食谱',
    chef_generating: '正在烹饪食谱...',
    chef_add_to_log: '添加到日志',
    chef_ingredients: '食材',
    chef_instructions: '步骤',
    chef_no_remaining: '已达到目标！增加目标以生成更多餐点。',
    chef_time: '时间',
    chef_error: '大厨把饭烧焦了（错误）。请重试！',
    remaining_cals: '剩余',
    save_recipe: '保存到食谱书',
    recipe_saved: '食谱已保存！',
    cookbook_title: '我的食谱书',
    cookbook_desc: '您的AI生成食谱收藏。',
    no_recipes: '尚未保存食谱。',
    no_recipes_hint: '使用 ChefMini 生成并保存美味食谱。',
    view_recipe: '查看食谱',
    log_this_meal: '记录此餐',
    delete_recipe: '删除食谱',
    chef_prompt_label: '有什么特别想吃的吗？（可选）',
    chef_prompt_placeholder: '例如："辣味鸡肉面"，"素食"，"快速早餐"',
    shopping_list_title: '购物清单',
    shopping_list_desc: '管理您的食材和杂货。',
    add_item: '添加项目',
    add_to_shopping: '添加到购物清单',
    added_to_shopping: '已添加',
    clear_completed: '清除已完成',
    no_items: '您的购物清单是空的。',
    no_items_hint: '手动添加或从食谱导出。',
    confirm_delete_title: '确认删除',
    delete_btn: '删除',
    delete_recipe_confirm: '确定要删除此食谱吗？',
    welcome_back: '欢迎回来',
    welcome_desc: '登录以访问您的计划。',
    create_account: '创建账户',
    create_desc: '今天开始您的营养之旅。',
    email_label: '电子邮件',
    password_label: '密码',
    name_label: '全名',
    login_btn: '登录',
    register_btn: '注册',
    continue_google: '继续使用 Google',
    continue_apple: '继续使用 Apple',
    switch_to_register: "没有账户？注册",
    switch_to_login: '已有账户？登录',
    logout: '登出',
    auth_error: '凭据无效。',
    auth_exists: '用户已存在。',
    guest_continue: '以访客身份继续'
  }
};